// Build src/vader.js from the VADER sentiment lexicon.
//
//   node scripts/vader.mjs [path/to/vader_lexicon.txt]
//
// Without a path it downloads the file from the VADER repository. The output
// is a plain object of word -> valence on the engine's -1..1 scale, filtered
// so it adds coverage without adding noise:
//
//   - alphabetic words only (no emoticons, no acronyms with digits)
//   - only words the raters felt at least moderately about (|mean| >= 1.5 of 4),
//     rescaled so 1.5 lands just above the editorial threshold and 4 is 1
//   - nothing that already belongs to another channel (negators, hedges,
//     intensifiers, contrast and surprise markers), including their stems,
//     so "honestly" stays a hedge rather than borrowing "honest"
//   - a short list of words VADER rates by their happiest sense, which in
//     prose about software are almost always the other sense
//
// Hand entries in lexicon.js win over anything here.

import { readFileSync, writeFileSync } from 'node:fs';
import { CERTAINTY, SURPRISE, INTENSIFIERS, NEGATORS, CONTRAST, stems } from '../src/lexicon.js';

const SOURCE = 'https://raw.githubusercontent.com/cjhutto/vaderSentiment/master/vaderSentiment/vader_lexicon.txt';
const MIN = 1.5;

const POLYSEMOUS = [
  'hand', 'free', 'freely', 'like', 'likes', 'liked', 'play', 'plays', 'played', 'share', 'shares',
  'shared', 'please', 'want', 'wants', 'wanted', 'kind', 'pretty', 'fine', 'fair', 'mean', 'means',
  'well', 'cool', 'clear', 'clearly', 'sure', 'right', 'save', 'saved', 'saves', 'safe', 'help',
  'helps', 'helped', 'support', 'supported', 'supports', 'care', 'cares', 'join', 'joined', 'ok',
  'okay', 'yes', 'good', 'great', 'top', 'party', 'fun', 'interest', 'interested', 'interesting',
  'value', 'values', 'worth', 'credit', 'award', 'awards', 'grant', 'granted', 'trust', 'trusted',
  'commit', 'committed', 'master', 'kill', 'killed', 'kills', 'abort', 'aborted', 'dump', 'dumped',
  'terminate', 'terminated', 'execute', 'executed', 'die', 'dies', 'died',
];
// kill, abort, dump, terminate, execute and die are kept after all when they
// are not process verbs; the hand lexicon decides those, so they are dropped
// here and re-added below only for the plain human sense.
const KEEP_ANYWAY = { die: -0.6, died: -0.6, dies: -0.6 };

const other = new Set();
for (const w of [...Object.keys(CERTAINTY), ...Object.keys(SURPRISE), ...Object.keys(INTENSIFIERS), ...NEGATORS, ...CONTRAST, ...POLYSEMOUS]) {
  other.add(w);
  for (const s of stems(w)) other.add(s);
}

const text = process.argv[2] ? readFileSync(process.argv[2], 'utf8') : await (await fetch(SOURCE)).text();
const out = {};
let seen = 0;
for (const line of text.split('\n')) {
  const [word, mean] = line.split('\t');
  if (!word || !/^[a-z]+$/.test(word)) continue;
  seen++;
  const v = Number(mean);
  if (!Number.isFinite(v) || Math.abs(v) < MIN || other.has(word)) continue;
  out[word] = Math.round(Math.sign(v) * ((Math.abs(v) - 1) / 3) * 100) / 100;
}
Object.assign(out, KEEP_ANYWAY);

const entries = Object.entries(out).sort(([a], [b]) => (a < b ? -1 : 1));
const lines = [];
let line = ' ';
for (const [w, v] of entries) {
  const piece = ` ${w}: ${v},`;
  if (line.length + piece.length > 96) { lines.push(line); line = ' '; }
  line += piece;
}
if (line.trim()) lines.push(line);

writeFileSync(new URL('../src/vader.js', import.meta.url), `// Generated by scripts/vader.mjs from the VADER sentiment lexicon. Do not edit.
//
// VADER: Hutto, C.J. & Gilbert, E.E. (2014). VADER: A Parsimonious Rule-based
// Model for Sentiment Analysis of Social Media Text. Eighth International
// Conference on Weblogs and Social Media (ICWSM-14). Ann Arbor, MI.
// https://github.com/cjhutto/vaderSentiment
//
// The MIT License (MIT)
// Copyright (c) 2016 C.J. Hutto
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// ${entries.length} of ${seen} alphabetic entries kept: |mean| >= ${MIN} of 4, rescaled to
// (|mean| - 1) / 3 on the engine's -1..1 scale, minus words that belong to
// another channel and a short list of words rated by their happiest sense.

export const VADER = {
${lines.join('\n')}
};
`);
console.log(`src/vader.js: ${entries.length} entries from ${seen}`);
